### ISSUE TITLE
Disable auto capitalize behavior for inputs

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/personal-logger#17]
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize

**Comment by MikeTheCanuck** [comment]
Happy to take this one and run with it @bvaughn - leveraging this behaviour is something I need to do for my own project as well.  As long as you're not already underway, I'll marshall a PR for ya.

**Comment by bvaughn** [comment]
Sounds great! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by MikeTheCanuck** [comment]
I observe that the default `autocapitalization = "sentences"` behaviour is in play when browsing to https://personal-logger.now.sh from mobile Safari (iOS 11.2.1).

I observe *no* auto-capitalization behaviour when browsing the app (at either localhost or personal-logger.now.sh) from "desktop" Safari or Chrome - OS 10.13.2, Chrome 63.

I don't believe I've done anything to Accessibility or Keyboard settings that would impose a non-default behaviour here.

I've also tried to test this by browsing to the dev server (e.g. http://192.168.1.5:3000) from both mobile Safari and mobile Chrome on my iPhone, and in both cases the "Sign in using..." buttons for GitHub and Twitter depress but otherwise do nothing (i.e. I cannot proceed past authentication to the Edit forms to start interacting with the autocap behaviours).

This has me at a loss - I'm unable to see autocap behaviour from desktop testing, and I'm currently unable to interact with the dev server from my mobile browsers because I can't get authentication to kick off.

(I swear I'm trying to be helpful but I would understand if my 'contributions' appeared less helpful and more complaint- and distraction-oriented.)

I'll continue to look for a way to browse my dev server from a mobile device - might have to resurrect an ancient device - or otherwise emulate the default behaviour of the mobile browser.

**Comment by bvaughn** [comment]
Pretty sure this is an iOS-specific property. You would probably need to test locally using a simulator. The Firebase backend for this app only auths for localhost or the personal-logger domain. (Maybe you could use a host file to fake this... dunno)

**Comment by MikeTheCanuck** [comment]
Update: installing XCode and running its iPhone simulator (launch `Simulator` from XCode, launch mobile Safari, browse to http://localhost:3000/, authenticate using Twitter, open an Edit view, start typing sentences in a string input control) demonstrates the `autocapitalization = sentences` default behaviour we're expecting.

Merry Christmas to all - this (presumably-trivial) PR should proceed when I get another break from the holidaying.

**Comment by MikeTheCanuck** [comment]
According to MDN, yes indeed this is only supported by iOS Safari:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form

I was experimenting with the various values in the XCode iPhone Simulator and the "words" value behaved differently than I expected - whereas I expected it to capitalize the *first* character of every word, in fact it seems to capitalize the first character of the first word of a sentence *and* capitalize the second character of every word (e.g. "THe qUick bRown fOx").  Not that this is needed at this time, but something to note in case we don't get exactly the behaviour we're expecting.

**Comment by bvaughn** [comment]
Fixed by PR #20!

**Comment by bvaughn** [comment]
And it's just been deployed~
