### ISSUE TITLE
Protect app from unauthorized users

### ISSUE THREAD

**Issue by jaabiri** [bvaughn/personal-logger#34]
Thank you for sharing the code It was really helpfull.
I was playing with the React Dev Tools, I found that I can be redirected to the main page without authentication 
How can I stop the page from being rendered ?
![demo](https://user-images.githubusercontent.com/7157261/36635500-45fb85fc-19b6-11e8-85bd-b72e279934f8.gif)

**Comment by bvaughn** [comment]
You're welcome. 😄

The app (or more accurately and more importantly, the data) is protected unauthorized users. Manually editing component-state like this will just result in a navigation header that doesn't work and a loading spinner that will never get dismissed.

It's possible to change the components so that even these won't be accessible, but I don't know if it's worth the effort. Direct URL navigation (by far the most common) will load the login route. I don't think many people will use DevTools in the way you are, and even if they do, they won't get any important data. 😄

That being said, if you'd like to submit a PR, I'll be happy to review it.
